# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true
    rate_limiter:
        username_ip_login:
            policy: token_bucket
            limit: 5
            rate: { interval: '5 minutes' }
            cache_pool: 'cache.redis'

        ip_login:
            policy: sliding_window
            limit: 50
            interval: '15 minutes'
            cache_pool: 'cache.redis'
    cache:
        pools:
            cache.redis:
                adapter: 'cache.adapter.redis'
                provider: 'redis://%env(REDIS_LISTEN_IP)%:%env(REDIS_LISTEN_PORT)%?auth=%env(REDIS_PASSWORD)%'

    assets:
        version: '%env(DOCKONTROL_VERSION)%'
        version_format: '%%s?version=%%s'
when@test:
    framework:
        test: true
        profiler:
            enabled: false
        session:
            storage_factory_id: session.storage.factory.mock_file
